# Generated by Django 5.0.6 on 2025-04-27 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_app', '0008_reciperequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery_app.recipecategory'),
        ),
    ]
