services:
  - type: web
    name: grocery-backend
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn grocery_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-render-db-name
          property: connectionString
      - key: SECRET_KEY
        value: your-django-secret-key
      - key: DEBUG
        value: false
      - key: OPENAI_API_KEY
        value: your-openai-key-here
